// Detection patterns for TypeScript / JavaScript (Node.js) stack
export const STACK_ID = "nodejs";

export const DETECTORS = [
  {
    id: "openai-compatible-llm",
    stack: "OpenAI",
    autoScope: "external",
    markerLabel: "OpenAI-compatible chat completions",
    passportFileName: "integration-passport.openai-compatible-llm.md",
    patterns: [/\bOpenAiCompatibleLlmClient\b/i, /\/v1\/chat\/completions/i, /\bOpenAI\b/i],
  },
  {
    id: "grpc-integration",
    stack: "gRPC",
    autoScope: null,
    markerLabel: "gRPC integration",
    passportFileName: "integration-passport.grpc-integration.md",
    patterns: [/from\s+['"]@grpc\//i, /require\s*\(\s*['"]@grpc\//i],
  },
  {
    id: "graphql-integration",
    stack: "GraphQL",
    autoScope: null,
    markerLabel: "GraphQL integration",
    passportFileName: "integration-passport.graphql-integration.md",
    patterns: [
      /\bnew\s+ApolloClient\b/,
      /\bnew\s+GraphQLClient\b/,
      /\bApolloProvider\b/,
      /from\s+['"]graphql['"]/i,
      /from\s+['"]@apollo\//i,
      /require\s*\(\s*['"]graphql['"]\s*\)/i,
      /gql\s*`/,
    ],
  },
  {
    id: "soap-integration",
    stack: "SOAP",
    autoScope: null,
    markerLabel: "SOAP integration",
    passportFileName: "integration-passport.soap-integration.md",
    patterns: [/from\s+['"]soap['"]/i, /require\s*\(\s*['"]soap['"]\s*\)/i, /\.wsdl\b/i],
  },
  {
    id: "sftp-integration",
    stack: "SFTP",
    autoScope: null,
    markerLabel: "SFTP integration",
    passportFileName: "integration-passport.sftp-integration.md",
    patterns: [/from\s+['"]ssh2-sftp-client['"]/i, /from\s+['"]ssh2['"]/i, /require\s*\(\s*['"]ssh2['"]\s*\)/i],
  },
  {
    id: "kafka-integration",
    stack: "Kafka",
    autoScope: null,
    markerLabel: "Kafka integration",
    passportFileName: "integration-passport.kafka-integration.md",
    patterns: [/\bnew\s+Kafka\b/, /from\s+['"]kafkajs['"]/i, /require\s*\(\s*['"]kafkajs['"]\s*\)/i],
  },
  {
    id: "rabbitmq-integration",
    stack: "RabbitMQ",
    autoScope: null,
    markerLabel: "RabbitMQ integration",
    passportFileName: "integration-passport.rabbitmq-integration.md",
    patterns: [/amqp:\/\//, /from\s+['"]amqplib['"]/i, /require\s*\(\s*['"]amqplib['"]\s*\)/i],
  },
  {
    id: "webhook-integration",
    stack: "Webhook",
    autoScope: null,
    markerLabel: "Webhook integration",
    passportFileName: "integration-passport.webhook-integration.md",
    patterns: [/\bWebhookClient\b/i, /\bWebhookSender\b/i, /\bWebhookReceiver\b/i, /X-Hub-Signature\b/i, /X-Webhook-Signature\b/i],
  },
  {
    id: "external-http-api",
    stack: "REST",
    autoScope: null,
    markerLabel: "External HTTP API",
    passportFileName: "integration-passport.external-http-api.md",
    patterns: [
      /(?:url|endpoint|baseUrl|baseUri|baseAddress|host)\s*(?:=|:)\s*["'`]https?:\/\//i,
      /new\s+URL\s*\(\s*["'`]https?:\/\//i,
    ],
    configPatterns: [/https?:\/\/(?!localhost\b|127\.|0\.0\.0\.0\b)[a-zA-Z0-9][\w.-]*\.[a-zA-Z]{2,}/i],
  },
  {
    id: "s3-object-storage",
    stack: "S3",
    autoScope: "external",
    markerLabel: "S3 / Object Storage",
    passportFileName: "integration-passport.s3-object-storage.md",
    patterns: [
      /from\s+['"]@aws-sdk\/client-s3['"]/i,
      /require.*['"]@aws-sdk\/client-s3['"]/i,
      /from\s+['"]@azure\/storage-blob['"]/i,
      /\bBlobServiceClient\b/,
      /from\s+['"]@google-cloud\/storage['"]/i,
      /\bMinioClient\b/i,
      /require.*['"]minio['"]/i,
    ],
  },
  {
    id: "redis-cache",
    stack: "Redis",
    autoScope: null,
    markerLabel: "Redis",
    passportFileName: "integration-passport.redis-cache.md",
    patterns: [/from\s+['"]ioredis['"]/i, /from\s+['"]redis['"]/i, /require.*['"]ioredis['"]/i, /require.*['"]redis['"]/i],
  },
  {
    id: "sharepoint-graph",
    stack: "Graph/SharePoint",
    autoScope: "external",
    markerLabel: "Microsoft Graph / SharePoint",
    passportFileName: "integration-passport.sharepoint-graph.md",
    patterns: [/from\s+['"]@microsoft\/microsoft-graph-client['"]/i, /\bGraphServiceClient\b/],
  },
  {
    id: "smtp-email",
    stack: "SMTP",
    autoScope: "external",
    markerLabel: "SMTP / Email",
    passportFileName: "integration-passport.smtp-email.md",
    patterns: [
      /from\s+['"]nodemailer['"]/i,
      /require.*['"]nodemailer['"]/i,
      /from\s+['"]@sendgrid\/mail['"]/i,
      /\bSendGridClient\b/i,
    ],
  },
  {
    id: "elasticsearch",
    stack: "Elasticsearch",
    autoScope: null,
    markerLabel: "Elasticsearch",
    passportFileName: "integration-passport.elasticsearch.md",
    patterns: [/from\s+['"]@elastic\/elasticsearch['"]/i],
  },
  {
    id: "stripe-payments",
    stack: "Stripe",
    autoScope: "external",
    markerLabel: "Stripe Payments",
    passportFileName: "integration-passport.stripe-payments.md",
    patterns: [/from\s+['"]stripe['"]/i, /require.*['"]stripe['"]/i, /\bnew\s+Stripe\s*\(/],
  },
  {
    id: "oauth-sso",
    stack: "OAuth/SSO",
    autoScope: "external",
    markerLabel: "OAuth / SSO",
    passportFileName: "integration-passport.oauth-sso.md",
    patterns: [
      /from\s+['"]openid-client['"]/i,
      /from\s+['"]@azure\/msal-node['"]/i,
      /from\s+['"]@okta\/[^'"]+['"]/i,
      /from\s+['"]passport['"]/i,
    ],
  },
  {
    id: "db-postgresql",
    stack: "PostgreSQL",
    autoScope: null,
    markerLabel: "PostgreSQL",
    passportFileName: "integration-passport.db-postgresql.md",
    patterns: [/from\s+['"]pg['"]/i, /require.*['"]pg['"]/i, /\bnew\s+Pool\b/],
  },
  {
    id: "db-mysql",
    stack: "MySQL",
    autoScope: null,
    markerLabel: "MySQL",
    passportFileName: "integration-passport.db-mysql.md",
    patterns: [/from\s+['"]mysql2['"]/i, /require.*['"]mysql2['"]/i],
  },
  {
    id: "db-mongodb",
    stack: "MongoDB",
    autoScope: null,
    markerLabel: "MongoDB",
    passportFileName: "integration-passport.db-mongodb.md",
    patterns: [/\bnew\s+MongoClient\b/, /from\s+['"]mongoose['"]/i, /require.*['"]mongoose['"]/i],
  },
  {
    id: "db-mssql",
    stack: "SQL Server",
    autoScope: null,
    markerLabel: "SQL Server",
    passportFileName: "integration-passport.db-mssql.md",
    patterns: [/from\s+['"]mssql['"]/i, /require.*['"]mssql['"]/i],
  },
  {
    id: "db-oracle",
    stack: "Oracle",
    autoScope: null,
    markerLabel: "Oracle",
    passportFileName: "integration-passport.db-oracle.md",
    patterns: [/from\s+['"]oracledb['"]/i, /require.*['"]oracledb['"]/i],
  },
  {
    id: "db-sqlite",
    stack: "SQLite",
    autoScope: "internal",
    markerLabel: "SQLite",
    passportFileName: "integration-passport.db-sqlite.md",
    patterns: [/from\s+['"]better-sqlite3['"]/i, /from\s+['"]sqlite3['"]/i, /require.*['"]sqlite3['"]/i],
  },
];
