// Detection patterns for C# / .NET stack
export const STACK_ID = "dotnet";

export const DETECTORS = [
  {
    id: "grpc-integration",
    stack: "gRPC",
    autoScope: null,
    markerLabel: "gRPC integration",
    passportFileName: "integration-passport.grpc-integration.md",
    patterns: [/\bGrpcChannel\b/, /\bGrpcClient\b/],
  },
  {
    id: "graphql-integration",
    stack: "GraphQL",
    autoScope: null,
    markerLabel: "GraphQL integration",
    passportFileName: "integration-passport.graphql-integration.md",
    patterns: [/\bnew\s+ApolloClient\b/, /\bnew\s+GraphQLClient\b/, /\bApolloProvider\b/],
  },
  {
    id: "soap-integration",
    stack: "SOAP",
    autoScope: null,
    markerLabel: "SOAP integration",
    passportFileName: "integration-passport.soap-integration.md",
    patterns: [/\bSoapClient\b/i, /\bBasicHttpBinding\b/, /\bServiceReference\b/, /\.wsdl\b/i],
  },
  {
    id: "sftp-integration",
    stack: "SFTP",
    autoScope: null,
    markerLabel: "SFTP integration",
    passportFileName: "integration-passport.sftp-integration.md",
    patterns: [/\bSftpClient\b/i, /\bRenci\.SshNet\b/],
  },
  {
    id: "kafka-integration",
    stack: "Kafka",
    autoScope: null,
    markerLabel: "Kafka integration",
    passportFileName: "integration-passport.kafka-integration.md",
    patterns: [/\bKafkaConsumer\b/, /\bKafkaProducer\b/, /\bKafkaClient\b/, /\bConfluent\.Kafka\b/],
  },
  {
    id: "rabbitmq-integration",
    stack: "RabbitMQ",
    autoScope: null,
    markerLabel: "RabbitMQ integration",
    passportFileName: "integration-passport.rabbitmq-integration.md",
    patterns: [/amqp:\/\//, /\bBasicPublish\b/, /\bBasicConsume\b/, /\bRabbitMQ\.Client\b/i],
  },
  {
    id: "webhook-integration",
    stack: "Webhook",
    autoScope: null,
    markerLabel: "Webhook integration",
    passportFileName: "integration-passport.webhook-integration.md",
    patterns: [/\bWebhookClient\b/i, /\bWebhookSender\b/i, /\bWebhookReceiver\b/i, /X-Hub-Signature\b/i, /X-Webhook-Signature\b/i],
  },
  {
    id: "external-http-api",
    stack: "REST",
    autoScope: null,
    markerLabel: "External HTTP API",
    passportFileName: "integration-passport.external-http-api.md",
    patterns: [
      /\bAddHttpClient\b/i,
      /\bHttpClient\b/i,
      /(?:url|endpoint|baseUrl|baseUri|baseAddress|host)\s*(?:=|:)\s*["'`]https?:\/\//i,
      /new\s+Uri\s*\(\s*["'`]https?:\/\//i,
    ],
    configPatterns: [/https?:\/\/(?!localhost\b|127\.|0\.0\.0\.0\b)[a-zA-Z0-9][\w.-]*\.[a-zA-Z]{2,}/i],
  },
  {
    id: "s3-object-storage",
    stack: "S3",
    autoScope: "external",
    markerLabel: "S3 / Object Storage",
    passportFileName: "integration-passport.s3-object-storage.md",
    patterns: [/\bAmazonS3Client\b/, /\bnew\s+S3\s*\(/, /\bIAmazonS3\b/],
  },
  {
    id: "redis-cache",
    stack: "Redis",
    autoScope: null,
    markerLabel: "Redis",
    passportFileName: "integration-passport.redis-cache.md",
    patterns: [/\bConnectionMultiplexer\.Connect\b/, /\bStackExchange\.Redis\b/],
  },
  {
    id: "sharepoint-graph",
    stack: "Graph/SharePoint",
    autoScope: "external",
    markerLabel: "Microsoft Graph / SharePoint",
    passportFileName: "integration-passport.sharepoint-graph.md",
    patterns: [/\bGraphServiceClient\b/, /\bSPHttpClient\b/, /Microsoft\.Graph\b/],
  },
  {
    id: "smtp-email",
    stack: "SMTP",
    autoScope: "external",
    markerLabel: "SMTP / Email",
    passportFileName: "integration-passport.smtp-email.md",
    patterns: [/\bSmtpClient\b/, /\bMailKit\b/, /\bMimeMessage\b/],
  },
  {
    id: "elasticsearch",
    stack: "Elasticsearch",
    autoScope: null,
    markerLabel: "Elasticsearch",
    passportFileName: "integration-passport.elasticsearch.md",
    patterns: [/\bElasticClient\b/, /\bElasticsearchClient\b/, /\bNEST\b/],
  },
  {
    id: "stripe-payments",
    stack: "Stripe",
    autoScope: "external",
    markerLabel: "Stripe Payments",
    passportFileName: "integration-passport.stripe-payments.md",
    patterns: [/\bStripeClient\b/, /\bStripe\.\w+Service\b/],
  },
  {
    id: "oauth-sso",
    stack: "OAuth/SSO",
    autoScope: "external",
    markerLabel: "OAuth / SSO",
    passportFileName: "integration-passport.oauth-sso.md",
    patterns: [/\bMsalPublicClientApplication\b/, /\bMsalConfidentialClientApplication\b/, /\bOpenIdConnectOptions\b/],
  },
  {
    id: "db-postgresql",
    stack: "PostgreSQL",
    autoScope: null,
    markerLabel: "PostgreSQL",
    passportFileName: "integration-passport.db-postgresql.md",
    patterns: [/\bNpgsqlConnection\b/, /\bNpgsqlDataSource\b/],
  },
  {
    id: "db-mysql",
    stack: "MySQL",
    autoScope: null,
    markerLabel: "MySQL",
    passportFileName: "integration-passport.db-mysql.md",
    patterns: [/\bMySqlConnection\b/, /\bMySqlDataSource\b/],
  },
  {
    id: "db-mongodb",
    stack: "MongoDB",
    autoScope: null,
    markerLabel: "MongoDB",
    passportFileName: "integration-passport.db-mongodb.md",
    patterns: [/\bMongoClient\b/, /MongoDB\.Driver\b/],
  },
  {
    id: "db-mssql",
    stack: "SQL Server",
    autoScope: null,
    markerLabel: "SQL Server",
    passportFileName: "integration-passport.db-mssql.md",
    patterns: [/\bSqlConnection\b/, /\bMicrosoft\.Data\.SqlClient\b/],
  },
  {
    id: "db-oracle",
    stack: "Oracle",
    autoScope: null,
    markerLabel: "Oracle",
    passportFileName: "integration-passport.db-oracle.md",
    patterns: [/\bOracleConnection\b/, /Oracle\.ManagedDataAccess\b/],
  },
  {
    id: "db-sqlite",
    stack: "SQLite",
    autoScope: "internal",
    markerLabel: "SQLite",
    passportFileName: "integration-passport.db-sqlite.md",
    patterns: [/\bSQLiteConnection\b/, /Microsoft\.Data\.Sqlite\b/],
  },
];
