// Detection patterns for Java / Kotlin stack
export const STACK_ID = "java";

export const DETECTORS = [
  {
    id: "grpc-integration",
    stack: "gRPC",
    autoScope: null,
    markerLabel: "gRPC integration",
    passportFileName: "integration-passport.grpc-integration.md",
    patterns: [/\bManagedChannelBuilder\b/, /\bio\.grpc\b/],
  },
  {
    id: "graphql-integration",
    stack: "GraphQL",
    autoScope: null,
    markerLabel: "GraphQL integration",
    passportFileName: "integration-passport.graphql-integration.md",
    patterns: [/['"]graphql-java[^'"]*['"]/i],
  },
  {
    id: "soap-integration",
    stack: "SOAP",
    autoScope: null,
    markerLabel: "SOAP integration",
    passportFileName: "integration-passport.soap-integration.md",
    patterns: [/\bJAXWSService\b/, /\bJaxWsPortProxyFactoryBean\b/, /\.wsdl\b/i],
  },
  {
    id: "kafka-integration",
    stack: "Kafka",
    autoScope: null,
    markerLabel: "Kafka integration",
    passportFileName: "integration-passport.kafka-integration.md",
    patterns: [/\bKafkaProducer\b/, /\bKafkaConsumer\b/, /\borg\.apache\.kafka\b/],
  },
  {
    id: "rabbitmq-integration",
    stack: "RabbitMQ",
    autoScope: null,
    markerLabel: "RabbitMQ integration",
    passportFileName: "integration-passport.rabbitmq-integration.md",
    patterns: [/\bConnectionFactory\b/, /\bcom\.rabbitmq\.client\b/],
  },
  {
    id: "external-http-api",
    stack: "REST",
    autoScope: null,
    markerLabel: "External HTTP API",
    passportFileName: "integration-passport.external-http-api.md",
    patterns: [
      /\bRestTemplate\b/,
      /\bWebClient\b/,
      /\bOkHttpClient\b/,
      /\bHttpClient\b/,
      /\bHttpURLConnection\b/,
    ],
    configPatterns: [/https?:\/\/(?!localhost\b|127\.|0\.0\.0\.0\b)[a-zA-Z0-9][\w.-]*\.[a-zA-Z]{2,}/i],
  },
  {
    id: "s3-object-storage",
    stack: "S3",
    autoScope: "external",
    markerLabel: "S3 / Object Storage",
    passportFileName: "integration-passport.s3-object-storage.md",
    patterns: [/\bS3Client\b/, /\bAmazonS3\b/, /\bcom\.amazonaws\.services\.s3\b/],
  },
  {
    id: "redis-cache",
    stack: "Redis",
    autoScope: null,
    markerLabel: "Redis",
    passportFileName: "integration-passport.redis-cache.md",
    patterns: [/\bJedis\b/, /\bLettuceClient\b/, /\bRedissonClient\b/],
  },
  {
    id: "smtp-email",
    stack: "SMTP",
    autoScope: "external",
    markerLabel: "SMTP / Email",
    passportFileName: "integration-passport.smtp-email.md",
    patterns: [/\bJavaMailSender\b/, /\bMimeMessage\b/, /\bSession\.getInstance\b/],
  },
  {
    id: "elasticsearch",
    stack: "Elasticsearch",
    autoScope: null,
    markerLabel: "Elasticsearch",
    passportFileName: "integration-passport.elasticsearch.md",
    patterns: [/\bElasticsearchClient\b/, /\bRestHighLevelClient\b/],
  },
  {
    id: "stripe-payments",
    stack: "Stripe",
    autoScope: "external",
    markerLabel: "Stripe Payments",
    passportFileName: "integration-passport.stripe-payments.md",
    patterns: [/\bStripe\.apiKey\b/, /\bcom\.stripe\b/],
  },
  {
    id: "oauth-sso",
    stack: "OAuth/SSO",
    autoScope: "external",
    markerLabel: "OAuth / SSO",
    passportFileName: "integration-passport.oauth-sso.md",
    patterns: [/\bOAuthRestTemplate\b/, /\bOAuth2AccessToken\b/, /\bspring\.security\.oauth2\b/],
  },
  {
    id: "db-postgresql",
    stack: "PostgreSQL",
    autoScope: null,
    markerLabel: "PostgreSQL",
    passportFileName: "integration-passport.db-postgresql.md",
    patterns: [/\borg\.postgresql\.Driver\b/, /['"]jdbc:postgresql:/i],
  },
  {
    id: "db-mysql",
    stack: "MySQL",
    autoScope: null,
    markerLabel: "MySQL",
    passportFileName: "integration-passport.db-mysql.md",
    patterns: [/\bcom\.mysql\.cj\.jdbc\.Driver\b/, /['"]jdbc:mysql:/i],
  },
  {
    id: "db-mongodb",
    stack: "MongoDB",
    autoScope: null,
    markerLabel: "MongoDB",
    passportFileName: "integration-passport.db-mongodb.md",
    patterns: [/\bMongoClient\b/, /\bcom\.mongodb\.client\b/],
  },
  {
    id: "db-mssql",
    stack: "SQL Server",
    autoScope: null,
    markerLabel: "SQL Server",
    passportFileName: "integration-passport.db-mssql.md",
    patterns: [/\bcom\.microsoft\.sqlserver\.jdbc\b/, /['"]jdbc:sqlserver:/i],
  },
  {
    id: "db-oracle",
    stack: "Oracle",
    autoScope: null,
    markerLabel: "Oracle",
    passportFileName: "integration-passport.db-oracle.md",
    patterns: [/\boracle\.jdbc\.driver\.OracleDriver\b/, /['"]jdbc:oracle:/i],
  },
  {
    id: "db-sqlite",
    stack: "SQLite",
    autoScope: "internal",
    markerLabel: "SQLite",
    passportFileName: "integration-passport.db-sqlite.md",
    patterns: [/\borg\.sqlite\.JDBC\b/, /['"]jdbc:sqlite:/i],
  },
];
