// Detection patterns for Python stack
export const STACK_ID = "python";

export const DETECTORS = [
  {
    id: "grpc-integration",
    stack: "gRPC",
    autoScope: null,
    markerLabel: "gRPC integration",
    passportFileName: "integration-passport.grpc-integration.md",
    patterns: [/import\s+grpc\b/i, /\bgrpc\.insecure_channel\b/, /\bgrpc\.secure_channel\b/],
  },
  {
    id: "kafka-integration",
    stack: "Kafka",
    autoScope: null,
    markerLabel: "Kafka integration",
    passportFileName: "integration-passport.kafka-integration.md",
    patterns: [/from\s+kafka\b/i, /import\s+kafka\b/i, /\bconfluent_kafka\b/i],
  },
  {
    id: "rabbitmq-integration",
    stack: "RabbitMQ",
    autoScope: null,
    markerLabel: "RabbitMQ integration",
    passportFileName: "integration-passport.rabbitmq-integration.md",
    patterns: [/\bpika\.BlockingConnection\b/, /\bpika\.connect\b/, /import\s+pika\b/i],
  },
  {
    id: "sftp-integration",
    stack: "SFTP",
    autoScope: null,
    markerLabel: "SFTP integration",
    passportFileName: "integration-passport.sftp-integration.md",
    patterns: [/\bparamiko\.SFTPClient\b/, /import\s+pysftp\b/i, /\bpysftp\.Connection\b/],
  },
  {
    id: "external-http-api",
    stack: "REST",
    autoScope: null,
    markerLabel: "External HTTP API",
    passportFileName: "integration-passport.external-http-api.md",
    patterns: [
      /\brequests\.(get|post|put|patch|delete|request)\s*\(/i,
      /\bhttpx\.Client\b/,
      /\baiohttp\.ClientSession\b/,
    ],
    configPatterns: [/https?:\/\/(?!localhost\b|127\.|0\.0\.0\.0\b)[a-zA-Z0-9][\w.-]*\.[a-zA-Z]{2,}/i],
  },
  {
    id: "s3-object-storage",
    stack: "S3",
    autoScope: "external",
    markerLabel: "S3 / Object Storage",
    passportFileName: "integration-passport.s3-object-storage.md",
    patterns: [
      /\bboto3\.client\s*\(\s*['"]s3['"]/i,
      /\bboto3\.resource\s*\(\s*['"]s3['"]/i,
      /from\s+azure\.storage\.blob\b/i,
    ],
  },
  {
    id: "redis-cache",
    stack: "Redis",
    autoScope: null,
    markerLabel: "Redis",
    passportFileName: "integration-passport.redis-cache.md",
    patterns: [/\bredis\.Redis\b/, /\bredis\.StrictRedis\b/, /import\s+redis\b/i, /\baioredis\.from_url\b/],
  },
  {
    id: "smtp-email",
    stack: "SMTP",
    autoScope: "external",
    markerLabel: "SMTP / Email",
    passportFileName: "integration-passport.smtp-email.md",
    patterns: [/\bsmtplib\.SMTP\b/, /from\s+email\b/i, /\bsendgrid\.SendGridAPIClient\b/],
  },
  {
    id: "elasticsearch",
    stack: "Elasticsearch",
    autoScope: null,
    markerLabel: "Elasticsearch",
    passportFileName: "integration-passport.elasticsearch.md",
    patterns: [/from\s+elasticsearch\b/i, /\bElasticsearch\s*\(/],
  },
  {
    id: "stripe-payments",
    stack: "Stripe",
    autoScope: "external",
    markerLabel: "Stripe Payments",
    passportFileName: "integration-passport.stripe-payments.md",
    patterns: [/import\s+stripe\b/i, /\bstripe\.api_key\b/],
  },
  {
    id: "oauth-sso",
    stack: "OAuth/SSO",
    autoScope: "external",
    markerLabel: "OAuth / SSO",
    passportFileName: "integration-passport.oauth-sso.md",
    patterns: [/from\s+authlib\b/i, /\bOAuth2Session\b/, /from\s+oauthlib\b/i],
  },
  {
    id: "db-postgresql",
    stack: "PostgreSQL",
    autoScope: null,
    markerLabel: "PostgreSQL",
    passportFileName: "integration-passport.db-postgresql.md",
    patterns: [/\bpsycopg2\.connect\b/, /\basyncpg\.connect\b/, /import\s+psycopg2\b/i],
  },
  {
    id: "db-mysql",
    stack: "MySQL",
    autoScope: null,
    markerLabel: "MySQL",
    passportFileName: "integration-passport.db-mysql.md",
    patterns: [/\bmysql\.connector\.connect\b/, /\baiomysql\.connect\b/],
  },
  {
    id: "db-mongodb",
    stack: "MongoDB",
    autoScope: null,
    markerLabel: "MongoDB",
    passportFileName: "integration-passport.db-mongodb.md",
    patterns: [/\bMongoClient\s*\(/, /from\s+pymongo\b/i],
  },
  {
    id: "db-mssql",
    stack: "SQL Server",
    autoScope: null,
    markerLabel: "SQL Server",
    passportFileName: "integration-passport.db-mssql.md",
    patterns: [/\bpyodbc\.connect\b/, /import\s+pyodbc\b/i],
  },
  {
    id: "db-sqlite",
    stack: "SQLite",
    autoScope: "internal",
    markerLabel: "SQLite",
    passportFileName: "integration-passport.db-sqlite.md",
    patterns: [/\bsqlite3\.connect\b/, /\baiosqlite\.connect\b/, /import\s+sqlite3\b/i],
  },
];
